### ISSUE TITLE
mega resume support

### ISSUE THREAD

**Issue by Sarfroz** [ZonD80/mega-downloader#17]
hi sir i was able to make resume support with mega files. But it's not completely done. The problem is the download manager shows resume capabiltiy . But if i stop and start it again, the resume start from 0. I hope you can help me little bit with this problem

**Comment by peter279k** [comment]
Hi @Sarfroz, thank you for your comment. I will help you add feature and send PR to the owner.
Thanks.

**Comment by ZonD80** [comment]
Resuming is not possible, because check another closed issues

**Comment by Sarfroz** [comment]
it is possible sir, its just we are not able to do so.

**Comment by ZonD80** [comment]
it is not possible unless you are saving positions of blocks for decryption and counting offsets for content-range requests based on decrypted chunk size for every file you are trying to resume to download (smart way), so, summary:

- Server must to download whole file to know what to send or/and save it somewhere to send part of it (dumb way)
- Server must seek to required encrypted chunk (and chunks are on fixed positions) (but anyway, it must to have info about where is this chunk in encrypted data, because length(plain_data)!=length(encrypted_data), so almost download of whole file again.....

So it's soooo complex and requires soo much space, sooo i personally give it up. I developed this script for stream downloads firstly as a proxy between mega and plain http(s)

**Comment by Sarfroz** [comment]
i am also fed up with this one, so i am using other service providers to
download the files

**Comment by enricodias** [comment]
@ZonD80 actually it is quite possible to do without saving data and without downloading the entire file again. Mega sends chunks of encrypted data with fixed size and it's possible to calculate the chunk number where your offset is and trim it as needed.

I was going to make a PR, but it seems like this project is no longer maintained.

**Comment by ZonD80** [comment]
Make a PR, I'm here

**Comment by Sarfroz** [comment]
Yes make it we all are here and we all need this feature. I am even ready
to donate for this.
