### ISSUE TITLE
[Suggestion] Pause/Continue download file

### ISSUE THREAD

**Issue by bebetoalves** [ZonD80/mega-downloader#5]
It would be possible to add this functionality? To pause and resume the download?

**Comment by ZonD80** [comment]
How do you see this in php script?

**Comment by bebetoalves** [comment]
http://stackoverflow.com/questions/1894299/php-remote-file-streaming-with-resume-support

**Comment by bebetoalves** [comment]
http://stackoverflow.com/questions/157318/resumable-downloads-when-using-php-to-send-the-file

**Comment by kkhendrik** [comment]
mega have encryption, possible for resume in php code?

**Comment by ZonD80** [comment]
I suppose no, because mega has steam cipher, that means that you need to decrypt first bytes of file in  order to decrypt further.
Plus, if you paused download, you need to save current pointer position somewhere, this will require additional persistent folder/storage.
And, finally, encrypted data length != decrypted data length, so you must to calculate offsets every time during browser requests some content range.

It is hard to implement + i really don't need such functionality now. If someone want to fund this research, go on:)
